project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!files/"
  resources:
    - "*.json"
    - "files"
    - "_extensions"


website:
  title: "d200x"
  navbar:
    right:
      - lectures.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



